# Generated by Django 4.0.2 on 2022-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_numberplate_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
