# Generated by Django 4.0.2 on 2022-02-13 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_numberplate_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='entrydate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
