# Generated by Django 4.0.2 on 2022-02-13 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_numberplate_entrydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
