# Generated by Django 4.0.2 on 2022-02-13 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_numberplate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='videofile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
