# Generated by Django 4.0.2 on 2022-02-22 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_numberplate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='vehicle_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
