# Generated by Django 4.0.2 on 2022-03-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_numberplate_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detections_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='recognition_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
