# Generated by Django 4.0.2 on 2022-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_image_detections_count_image_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='detections_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='recognition_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
