# Generated by Django 4.0.2 on 2022-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_rename_videofile_video_video_video_detections_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('entrydatetime', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(max_length=30)),
            ],
        ),
    ]
