# Generated by Django 4.0.2 on 2022-03-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_videonumberplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videonumberplate',
            old_name='entrydatetime',
            new_name='entrydate',
        ),
    ]
